name: CICD
on: pull_request
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Execute lint
        uses: ./.github/actions/lint
