name: CICD
on: pull_request
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: | 
          npm install
          npm i webdriver-manager@latest
          npm i chromedriver --chromedriver_version=LATEST
          npm uninstall protractor
          npm install --save-dev protractor
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: e2e
        run: npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js