name: CICD
on: pull_request
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        run: ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
      - name: e2e
        run: ng e2e --protractor-config=e2e/protractor-ci.conf.js