name: CICD
on: pull_request
jobs:
  Build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run lint
      - name: Test
        env:
          BROWSER: Chrome
        run: npm run test --no-watch --no-progress --browsers=ChromeHeadlessCI          
      - name: e2e
        env:
          BROWSER: Chrome
        run: npm run e2e --protractor-config=e2e/protractor-ci.conf.js          