name: package
on:
  push:
    branches:
      - master
jobs:
  package:
    name: package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master    
      - name: Install NodeJS
        uses: actions/setup-node@v1
        with:
          registry-url: https://npm.pkg.github.com/
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
