name: Stage
on:
  push:
    branches:
      - master
jobs:
  Stage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Install NodeJS
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install
      - name: Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run deploy -- --base-href=/AboutMe/